/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab8y;

public class Library {
	public static void main(String arg[]) {
		System.out.println("Yankees.");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
